dist: xenial
language: python
python:
  - "3.7"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install: make setup
script: make travis
deploy:
  skip_cleanup: true
  provider: script
  script: make travis-deploy
  on:
    branch: master
